const SB_URL="YOUR_SUPABASE_URL";const SB_KEY="YOUR_SUPABASE_PUBLISHABLE_KEY";
const db=window.supabase.createClient(SB_URL,SB_KEY);
const $=s=>document.querySelector(s);let user=null,profile=null,authMode="login";
const shop=[["hoodie","Forge Hoodie","🧥",100,"outfit"],["cyber","Cyber Hoodie","🧥",250,"outfit"],["gold","Golden Jacket","🥋",700,"outfit"],["ruby","Ruby Colour","🔴",150,"color"],["ocean","Ocean Colour","🔵",150,"color"],["green","Emerald Colour","🟢",150,"color"],["cap","Forge Cap","🧢",200,"hat"],["crown","Crown","👑",1000,"hat"],["wizard","Wizard Hat","🧙",750,"hat"],["glasses","Cool Glasses","🕶️",300,"accessory"],["star","Star Badge","⭐",400,"accessory"],["sparkles","Sparkles","✨",800,"accessory"]];
function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>x.classList.remove("show"),2300)}
function money(){let n=profile?.coins||0;$("#coinPill").textContent=`🪙 ${n}`;$("#shopCoins").textContent=n}
async function refresh(){const s=await db.auth.getSession();user=s.data.session?.user||null;if(user){const r=await db.from("profiles").select("*").eq("id",user.id).single();profile=r.data;$("#authBtn").textContent="Sign out";$("#heroUser").textContent=`Welcome, ${profile?.username||"Player"}!`;$("#heroSub").textContent=`🪙 ${profile?.coins||0} Forger Coins`;renderProfile()}else{$("#authBtn").textContent="Sign in";$("#heroUser").textContent="Welcome to ArcadeForge";$("#heroSub").textContent="Sign in to publish and save your profile"}money();loadGames();renderShop()}
async function loadGames(){let q=$("#search")?.value||"";let sort=$("#sort")?.value||"new";let query=db.from("games").select("id,title,description,icon,template,plays,likes,created_at,profiles(username)").eq("published",true);if(q)query=query.or(`title.ilike.%${q}%,description.ilike.%${q}%`);query=sort==="plays"?query.order("plays",{ascending:false}):sort==="likes"?query.order("likes",{ascending:false}):query.order("created_at",{ascending:false});let r=await query.limit(60);let games=r.data||[];renderGames(games);$("#gameCount").textContent=games.length;$("#featured").innerHTML=games.slice(0,6).map(card).join("")||empty("No community games yet.");}
function empty(t){return `<div class="panel center">${t}</div>`}
function card(g){return `<article class="card"><div class="cardArt">${g.icon||"🎮"}</div><div class="cardBody"><h3>${esc(g.title)}</h3><p>${esc(g.description||"")}</p><div class="meta"><span>by ${esc(g.profiles?.username||"Creator")} · ▶ ${g.plays||0}</span><button class="like" data-like="${g.id}">♥ ${g.likes||0}</button></div><button class="primary wide" data-play="${g.id}">Play</button></div></article>`}
function renderGames(games){$("#gamesGrid").innerHTML=games.map(card).join("")||empty("No games found.");$$("[data-play]").forEach(b=>b.onclick=()=>playGame(b.dataset.play));$$("[data-like]").forEach(b=>b.onclick=()=>likeGame(b.dataset.like))}
function $$ (s){return [...document.querySelectorAll(s)]}
async function likeGame(id){if(!user)return needLogin();let r=await db.rpc("toggle_game_like",{game_id:id});if(r.error)toast(r.error.message);else{toast(r.data?"❤️ Liked!":"Like removed");loadGames()}}
async function playGame(id){let r=await db.from("games").select("*").eq("id",id).single();if(r.error)return toast(r.error.message);await db.rpc("record_play",{game_id:id});$("#gameModal").classList.remove("hidden");launch(r.data)}
function launch(g){let m=$("#gameMount");m.innerHTML=`<div class="gameShell"><h2>${g.icon} ${esc(g.title)}</h2><p>${esc(g.description||"")}</p><div id="miniGame"></div></div>`;let a=$("#miniGame");if(g.template==="clicker")clicker(a);else if(g.template==="reaction")reaction(a);else if(g.template==="memory")memory(a);else if(g.template==="snake")snake(a);else dodger(a)}
function reward(n){if(user)db.rpc("award_game_coins",{amount:n}).then(()=>refresh())}
function clicker(a){let n=0,t=10;a.innerHTML=`<p>Score: <b id="cs">0</b> · <b id="ct">10</b>s</p><button class="bigAction" id="cb">💎 CLICK!</button>`;$("#cb").onclick=()=>{$("#cs").textContent=++n};let x=setInterval(()=>{if(--t<0){clearInterval(x);$("#cb").disabled=true;reward(Math.min(50,10+n));toast("Round complete!")}$("#ct").textContent=Math.max(0,t)},1000)}
function reaction(a){a.innerHTML=`<div class="reaction" id="rb">Wait for green…</div>`;let ready=false,start=0;setTimeout(()=>{ready=true;start=performance.now();$("#rb").style.background="#16a34a";$("#rb").textContent="CLICK NOW!"},1000+Math.random()*2500);$("#rb").onclick=()=>{if(!ready)return toast("Too early!");let ms=Math.round(performance.now()-start);$("#rb").textContent=`${ms} ms`;reward(Math.max(15,70-Math.floor(ms/10)))}}
function memory(a){let v=["🍎","🚀","⭐","🎮","💎","🐸","🔥","🌙"],c=[...v,...v].sort(()=>Math.random()-.5),open=[];a.innerHTML=`<div class="memory" id="mb"></div>`;c.forEach(x=>{let b=document.createElement("button");b.textContent="❔";b.onclick=()=>{if(b.textContent!=="❔"||open.length===2)return;b.textContent=x;open.push(b);if(open.length===2){let [p,q]=open;if(p.textContent===q.textContent){open=[];if($$("#mb button").every(z=>z.textContent!=="❔")){reward(60);toast("All matched!")}}else setTimeout(()=>{p.textContent=q.textContent="❔";open=[]},500)}};$("#mb").appendChild(b)})}
function snake(a){a.innerHTML=`<canvas width="480" height="480" id="sc"></canvas><p>Arrow keys to move.</p>`;let c=$("#sc"),x=c.getContext("2d"),s=[{x:10,y:10}],d={x:1,y:0},f={x:4,y:5},dead=false;function loop(){if(dead)return;let h={x:s[0].x+d.x,y:s[0].y+d.y};if(h.x<0||h.y<0||h.x>=20||h.y>=20||s.some(p=>p.x===h.x&&p.y===h.y)){dead=true;reward(20+s.length*3);return}s.unshift(h);if(h.x===f.x&&h.y===f.y)f={x:Math.random()*20|0,y:Math.random()*20|0};else s.pop();x.clearRect(0,0,480,480);x.font="22px sans-serif";x.fillText("🍎",f.x*24,f.y*24+21);s.forEach(p=>x.fillText("🟩",p.x*24,p.y*24+21));setTimeout(loop,130)}onkeydown=e=>{if(e.key==="ArrowUp"&&d.y!==1)d={x:0,y:-1};if(e.key==="ArrowDown"&&d.y!==-1)d={x:0,y:1};if(e.key==="ArrowLeft"&&d.x!==1)d={x:-1,y:0};if(e.key==="ArrowRight"&&d.x!==-1)d={x:1,y:0}};loop()}
function dodger(a){a.innerHTML=`<canvas width="640" height="360" id="dc"></canvas><p>Use A/D or ←/→. Survive!</p>`;let c=$("#dc"),x=c.getContext("2d"),px=300,rocks=[],start=performance.now();function loop(now){x.clearRect(0,0,640,360);if(Math.random()<.04)rocks.push({x:Math.random()*610,y:-20});if(event?.key==="ArrowLeft")px-=5;if(event?.key==="ArrowRight")px+=5;rocks.forEach(r=>r.y+=3);x.font="24px sans-serif";x.fillText("🚀",px,335);rocks.forEach(r=>x.fillText("☄️",r.x,r.y));if(rocks.some(r=>r.y>300&&Math.abs(r.x-px)<35)){reward(20);return}requestAnimationFrame(loop)}requestAnimationFrame(loop)}
function needLogin(){toast("Sign in first!");$("#authModal").classList.remove("hidden")}
function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function openAuth(mode){authMode=mode;$("#authTitle").textContent=mode==="login"?"Sign in":"Create account";$("#authSubmit").textContent=mode==="login"?"Sign in":"Sign up";$("#username").style.display=mode==="login"?"none":"block";$("#switchAuth").textContent=mode==="login"?"Need an account? Sign up":"Already have an account? Sign in";$("#authModal").classList.remove("hidden")}
$("#authBtn").onclick=async()=>{if(user){await db.auth.signOut();refresh()}else openAuth("login")};$("#profileSign").onclick=()=>openAuth("login");$("#switchAuth").onclick=()=>openAuth(authMode==="login"?"signup":"login");$$("[data-close]").forEach(x=>x.onclick=()=>x.closest(".modal").classList.add("hidden"));
$("#authForm").onsubmit=async e=>{e.preventDefault();let email=$("#email").value,password=$("#password").value;if(authMode==="login"){let r=await db.auth.signInWithPassword({email,password});if(r.error)$("#authMsg").textContent=r.error.message;else{$("#authModal").classList.add("hidden");refresh()}}else{let username=$("#username").value.trim();let r=await db.auth.signUp({email,password,options:{data:{username}}});if(r.error)$("#authMsg").textContent=r.error.message;else{$("#authMsg").textContent="Account created. Check your email if confirmation is enabled.";}}};
$("#createForm").onsubmit=async e=>{e.preventDefault();if(!user)return needLogin();let title=$("#gameName").value.trim(),description=$("#gameDesc").value.trim(),template=$("#gameType").value,icon=$("#gameIcon").value||"🎮";let r=await db.from("games").insert({title,description,template,icon,creator_id:user.id,published:true}).select().single();if(r.error)toast(r.error.message);else{await db.rpc("award_creator_coins");toast("🚀 Published to the community!");e.target.reset();$("#gameIcon").value="🎮";refresh();location.hash="games"}};
["gameName","gameDesc","gameIcon"].forEach(id=>$("#"+id).oninput=()=>{$("#previewName").textContent=$("#gameName").value||"Your Game";$("#previewDesc").textContent=$("#gameDesc").value||"Your description appears here.";$("#previewIcon").textContent=$("#gameIcon").value||"🎮"});
function renderShop(){if(!$("#shop"))return;$("#shop").innerHTML=shop.map(i=>`<div class="shopItem"><div class="icon">${i[2]}</div><b>${i[1]}</b><small>${i[4]}</small><div class="price"><span>🪙 ${i[3]}</span><button class="buy" data-buy="${i[0]}">Buy</button></div></div>`).join("");$$("[data-buy]").forEach(b=>b.onclick=()=>buy(b.dataset.buy))}
async function buy(id){if(!user)return needLogin();let r=await db.rpc("buy_cosmetic",{item_id:id});if(r.error)toast(r.error.message);else{toast("✨ Item unlocked!");refresh()}}
async function renderProfile(){if(!user)return;let inv=await db.from("inventory").select("item_id").eq("user_id",user.id);$("#profileContent").innerHTML=`<div class="profile"><div class="avatar">🧑</div><div><span class="eyebrow">PLAYER PROFILE</span><h1>${esc(profile?.username||"Player")}</h1><p>🪙 ${profile?.coins||0} Forger Coins</p><p>Games created: ${profile?.games_created||0} · Plays: ${profile?.plays||0}</p><p>Cosmetics owned: ${inv.data?.length||0}</p></div></div><hr><p class="hint">Your account, games, likes, coins and inventory are stored online.</p><button class="secondary" id="logout2">Sign out</button>`;$("#logout2").onclick=async()=>{await db.auth.signOut();refresh()}}
$("#search").oninput=loadGames;$("#sort").onchange=loadGames;
db.auth.onAuthStateChange(()=>setTimeout(refresh,0));
refresh();
