const SB_URL="YOUR_SUPABASE_URL";
const SB_KEY="YOUR_SUPABASE_PUBLISHABLE_KEY";
const db=window.supabase.createClient(SB_URL,SB_KEY);
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let user=null,profile=null,authMode="login";
const GAME_COST=1000, VIP_COST=5000, PASS_COST=2500;
const shop=[
 ["hoodie","Forge Hoodie","🧥",100,"Outfit"],["cyber","Cyber Hoodie","🧥",250,"Outfit"],["gold","Golden Jacket","🥋",700,"Outfit"],
 ["ruby","Ruby Colour","🔴",150,"Colour"],["ocean","Ocean Colour","🔵",150,"Colour"],["green","Emerald Colour","🟢",150,"Colour"],
 ["cap","Forge Cap","🧢",200,"Hat"],["crown","Crown","👑",1000,"Hat"],["wizard","Wizard Hat","🧙",750,"Hat"],
 ["glasses","Cool Glasses","🕶️",300,"Accessory"],["star","Star Badge","⭐",400,"Accessory"],["sparkles","Sparkles","✨",800,"Accessory"]
];
const passRewards=[
 [1,"🪙 300 Coins","coins",300],[2,"🧢 Forge Cap","item","cap"],[3,"🪙 500 Coins","coins",500],[4,"🧥 Cyber Hoodie","item","cyber"],[5,"🪙 750 Coins","coins",750],[6,"⭐ Star Badge","item","star"],[7,"🪙 1,000 Coins","coins",1000],[8,"🧙 Wizard Hat","item","wizard"],[9,"🪙 1,500 Coins","coins",1500],[10,"👑 Crown","item","crown"]
];
function toast(t){const x=$("#toast");x.textContent=t;x.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>x.classList.remove("show"),2600)}
function money(){const n=profile?.is_admin?"∞":(profile?.coins||0);$("#coinPill").textContent=`🪙 ${n}`;$("#shopCoins").textContent=n}
function needLogin(){toast("Sign in first!");openAuth("login")}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function isConfigured(){return !SB_URL.startsWith("YOUR_")&&!SB_KEY.startsWith("YOUR_")}
async function refresh(){
 if(!isConfigured()){toast("Add your Supabase URL and publishable key to app.js first.");return}
 const s=await db.auth.getSession(); user=s.data.session?.user||null; profile=null;
 if(user){const r=await db.from("profiles").select("*").eq("id",user.id).single();profile=r.data||null;$("#authBtn").textContent="Sign out";$("#heroUser").textContent=`${profile?.is_admin?"👑 ":""}Welcome, ${profile?.username||"Player"}!`;$("#heroSub").textContent=profile?.is_admin?"ADMIN · ∞ Forger Coins":`🪙 ${profile?.coins||0} Forger Coins · ${profile?.battle_xp||0} Battle XP`;await renderProfile();updatePass();}else{$("#authBtn").textContent="Sign in";$("#heroUser").textContent="Welcome to ArcadeForge";$("#heroSub").textContent="Sign in to save your profile and earn coins"}
 money();renderShop();loadGames();
}
async function loadGames(){if(!isConfigured())return;const q=$("#search")?.value||"",sort=$("#sort")?.value||"new";let query=db.from("games").select("id,title,description,icon,template,plays,likes,created_at,profiles(username)").eq("published",true);if(q)query=query.or(`title.ilike.%${q}%,description.ilike.%${q}%`);query=sort==="plays"?query.order("plays",{ascending:false}):sort==="likes"?query.order("likes",{ascending:false}):query.order("created_at",{ascending:false});const r=await query.limit(60);const games=r.data||[];renderGames(games);$("#gameCount").textContent=games.length;$("#featured").innerHTML=games.slice(0,6).map(card).join("")||empty("No community games yet.");
 const creators=new Set(games.map(g=>g.profiles?.username).filter(Boolean));$("#creatorCount").textContent=creators.size;$("#playCount").textContent=games.reduce((a,g)=>a+(g.plays||0),0);$("#leaderCount").textContent=profile?"1":"0";
}
function empty(t){return `<div class="panel center">${esc(t)}</div>`}
function card(g){return `<article class="card"><div class="cardArt">${esc(g.icon||"🎮")}</div><div class="cardBody"><h3>${esc(g.title)}</h3><p>${esc(g.description||"")}</p><div class="meta"><span>by ${esc(g.profiles?.username||"Creator")} · ▶ ${g.plays||0}</span><button class="like" data-like="${g.id}">♥ ${g.likes||0}</button></div><button class="primary wide" data-play="${g.id}">Play</button></div></article>`}
function renderGames(games){$("#gamesGrid").innerHTML=games.map(card).join("")||empty("No games found.");$$('[data-play]').forEach(b=>b.onclick=()=>playGame(b.dataset.play));$$('[data-like]').forEach(b=>b.onclick=()=>likeGame(b.dataset.like))}
async function likeGame(id){if(!user)return needLogin();const r=await db.rpc("toggle_game_like",{game_id:id});if(r.error)toast(r.error.message);else{toast(r.data?"❤️ Liked!":"Like removed");loadGames()}}
async function playGame(id){const r=await db.from("games").select("*").eq("id",id).single();if(r.error)return toast(r.error.message);const p=await db.rpc("record_play",{game_id:id});if(p.error)toast(p.error.message);$("#gameModal").classList.remove("hidden");launch(r.data);if(user){setTimeout(refresh,500)}}
function launch(g){const m=$("#gameMount");m.innerHTML=`<div class="gameShell"><h2>${esc(g.icon||"🎮")} ${esc(g.title)}</h2><p>${esc(g.description||"")}</p><div id="miniGame"></div></div>`;const a=$("#miniGame");if(g.template==="clicker")clicker(a);else if(g.template==="reaction")reaction(a);else if(g.template==="memory")memory(a);else if(g.template==="snake")snake(a);else dodger(a)}
function reward(n){if(user)db.rpc("award_game_coins",{amount:n}).then(r=>{if(r.error)toast(r.error.message);else refresh()})}
function clicker(a){let n=0,t=10,done=false;a.innerHTML=`<p>Score: <b id="cs">0</b> · <b id="ct">10</b>s</p><button class="bigAction" id="cb">💎 CLICK!</button>`;$("#cb").onclick=()=>{if(!done){n++;$("#cs").textContent=n}};const x=setInterval(()=>{t--;$("#ct").textContent=Math.max(0,t);if(t<=0){done=true;clearInterval(x);$("#cb").disabled=true;reward(Math.min(50,10+n));toast("Round complete! Coins + Battle XP earned.")}},1000)}
function reaction(a){a.innerHTML=`<div class="reaction" id="rb">Wait for green…</div>`;let ready=false,start=0,finished=false;const timer=setTimeout(()=>{ready=true;start=performance.now();$("#rb").classList.add("ready");$("#rb").textContent="CLICK NOW!"},1000+Math.random()*2500);$("#rb").onclick=()=>{if(finished)return;if(!ready){clearTimeout(timer);toast("Too early!");return}finished=true;const ms=Math.round(performance.now()-start);$("#rb").textContent=`${ms} ms`;reward(Math.max(15,70-Math.floor(ms/10)))}}
function memory(a){const v=["🍎","🚀","⭐","🎮","💎","🐸","🔥","🌙"],c=[...v,...v].sort(()=>Math.random()-.5),open=[];a.innerHTML=`<div class="memory" id="mb"></div>`;c.forEach(x=>{const b=document.createElement("button");b.textContent="❔";b.onclick=()=>{if(b.textContent!=="❔"||open.length===2)return;b.textContent=x;open.push(b);if(open.length===2){const[p,q]=open;if(p.textContent===q.textContent){open.length=0;if($$("#mb button").every(z=>z.textContent!=="❔")){reward(60);toast("All matched!")}}else setTimeout(()=>{p.textContent=q.textContent="❔";open.length=0},500)}};$("#mb").appendChild(b)})}
function snake(a){a.innerHTML=`<canvas width="480" height="480" id="sc"></canvas><p>Arrow keys to move.</p>`;const c=$("#sc"),x=c.getContext("2d"),s=[{x:10,y:10}],d={x:1,y:0};let f={x:4,y:5},dead=false;const key=e=>{if(e.key==="ArrowUp"&&d.y!==1){d.x=0;d.y=-1}if(e.key==="ArrowDown"&&d.y!==-1){d.x=0;d.y=1}if(e.key==="ArrowLeft"&&d.x!==1){d.x=-1;d.y=0}if(e.key==="ArrowRight"&&d.x!==-1){d.x=1;d.y=0}};window.addEventListener("keydown",key);function loop(){if(dead){window.removeEventListener("keydown",key);return}const h={x:s[0].x+d.x,y:s[0].y+d.y};if(h.x<0||h.y<0||h.x>=20||h.y>=20||s.some(p=>p.x===h.x&&p.y===h.y)){dead=true;reward(Math.min(50,20+s.length*3));toast("Snake over!");window.removeEventListener("keydown",key);return}s.unshift(h);if(h.x===f.x&&h.y===f.y){f={x:Math.random()*20|0,y:Math.random()*20|0}}else s.pop();x.clearRect(0,0,480,480);x.font="22px sans-serif";x.fillText("🍎",f.x*24,f.y*24+21);s.forEach(p=>x.fillText("🟩",p.x*24,p.y*24+21));setTimeout(loop,130)}loop()}
function dodger(a){a.innerHTML=`<canvas width="640" height="360" id="dc"></canvas><p>Use A/D or ←/→. Survive!</p>`;const c=$("#dc"),x=c.getContext("2d");let px=300,rocks=[],left=false,right=false,start=performance.now(),done=false;const kd=e=>{if(e.key==="ArrowLeft"||e.key.toLowerCase()==="a")left=true;if(e.key==="ArrowRight"||e.key.toLowerCase()==="d")right=true},ku=e=>{if(e.key==="ArrowLeft"||e.key.toLowerCase()==="a")left=false;if(e.key==="ArrowRight"||e.key.toLowerCase()==="d")right=false};window.addEventListener("keydown",kd);window.addEventListener("keyup",ku);function loop(now){if(done)return;x.clearRect(0,0,640,360);if(left)px-=6;if(right)px+=6;px=Math.max(0,Math.min(600,px));if(Math.random()<.04)rocks.push({x:Math.random()*610,y:-20});rocks.forEach(r=>r.y+=3);x.font="24px sans-serif";x.fillText("🚀",px,335);rocks.forEach(r=>x.fillText("☄️",r.x,r.y));if(rocks.some(r=>r.y>300&&Math.abs(r.x-px)<35)){done=true;reward(Math.min(50,20+Math.floor((now-start)/1000)));toast("You got hit! Reward earned.");window.removeEventListener("keydown",kd);window.removeEventListener("keyup",ku);return}requestAnimationFrame(loop)}requestAnimationFrame(loop)}
function openAuth(mode){authMode=mode;$("#authTitle").textContent=mode==="login"?"Sign in":"Create account";$("#authSubmit").textContent=mode==="login"?"Sign in":"Sign up";$("#username").style.display=mode==="login"?"none":"block";$("#switchAuth").textContent=mode==="login"?"Need an account? Sign up":"Already have an account? Sign in";$("#authMsg").textContent="";$("#authModal").classList.remove("hidden")}
$("#authBtn").onclick=async()=>{if(user){await db.auth.signOut();refresh()}else openAuth("login")};$("#profileSign").onclick=()=>openAuth("login");$("#switchAuth").onclick=()=>openAuth(authMode==="login"?"signup":"login");$$('[data-close]').forEach(x=>x.onclick=()=>x.closest(".modal").classList.add("hidden"));
$("#authForm").onsubmit=async e=>{e.preventDefault();if(!isConfigured())return toast("Connect Supabase in app.js first.");const email=$("#email").value,password=$("#password").value;if(authMode==="login"){const r=await db.auth.signInWithPassword({email,password});if(r.error)$("#authMsg").textContent=r.error.message;else{$("#authModal").classList.add("hidden");refresh()}}else{const username=$("#username").value.trim();if(!username)return $("#authMsg").textContent="Choose a username.";const r=await db.auth.signUp({email,password,options:{data:{username}}});if(r.error)$("#authMsg").textContent=r.error.message;else $("#authMsg").textContent="Account created. Check your email if confirmation is enabled."}};
function detectTemplate(p){p=p.toLowerCase();if(/snake|worm|grid/.test(p))return"snake";if(/memory|match|pairs|cards/.test(p))return"memory";if(/reaction|reflex|quick|speed|fast/.test(p))return"reaction";if(/space|meteor|dodge|survive|rocket/.test(p))return"dodger";return"clicker"}
function aiName(p,t){if($("#aiName").value.trim())return $("#aiName").value.trim();const names={snake:"Neon Snake Arena",memory:"Memory Mayhem",reaction:"Reaction Rush",dodger:"Meteor Escape",clicker:"Crystal Clicker X"};return names[t]}
$("#aiPrompt").oninput=()=>{const p=$("#aiPrompt").value.trim(),t=detectTemplate(p);$("#previewName").textContent=$("#aiName").value.trim()||"AI will name it";$("#previewDesc").textContent=p||"Describe your idea and the generator will build it here.";$("#previewType").textContent=p?`Template detected: ${t}`:"Waiting for idea…"};
["aiName","aiIcon"].forEach(id=>$("#"+id).oninput=()=>{$("#previewName").textContent=$("#aiName").value||"AI will name it";$("#previewIcon").textContent=$("#aiIcon").value||"🤖"});
$("#aiForm").onsubmit=async e=>{e.preventDefault();if(!user)return needLogin();const prompt=$("#aiPrompt").value.trim();if(!prompt)return;const template=detectTemplate(prompt),title=aiName(prompt,template),description=prompt.slice(0,160),icon=$("#aiIcon").value||"🤖";const r=await db.rpc("create_game_paid",{p_title:title,p_description:description,p_template:template,p_icon:icon});if(r.error)toast(r.error.message);else{toast("🤖 Game forged! 1,000 coins spent.");e.target.reset();$("#aiIcon").value="🤖";refresh();location.hash="games"}};
function renderShop(){const grid=$("#shopGrid");if(!grid)return;grid.innerHTML=`<div class="shopItem vipItem"><div class="icon">👑</div><b>VIP</b><small>VIP badge + special profile status</small><div class="price"><span>🪙 5,000</span><button class="buy" id="buyVip">Buy VIP</button></div></div>`+shop.map(i=>`<div class="shopItem"><div class="icon">${i[2]}</div><b>${i[1]}</b><small>${i[4]}</small><div class="price"><span>🪙 ${i[3]}</span><button class="buy" data-buy="${i[0]}">Buy</button></div></div>`).join("");$("#buyVip").onclick=buyVip;$$('[data-buy]').forEach(b=>b.onclick=()=>buy(b.dataset.buy))}
async function buyVip(){if(!user)return needLogin();const r=await db.rpc("buy_vip");if(r.error)toast(r.error.message);else{toast("👑 VIP unlocked!");refresh()}}
async function buy(id){if(!user)return needLogin();const r=await db.rpc("buy_cosmetic",{item_id:id});if(r.error)toast(r.error.message);else{toast("✨ Item unlocked!");refresh()}}
function renderPass(){const grid=$("#battleRewards");grid.innerHTML=passRewards.map(r=>`<div class="reward ${((profile?.battle_xp||0)>=r[0]*100)?"ready":""}"><b>Tier ${r[0]}</b><span>${r[1]}</span><small>${profile?.battle_pass?((profile?.battle_xp||0)>=r[0]*100?"Unlocked":"Locked until "+(r[0]*100)+" XP"):"Buy the pass to unlock"}</small><button class="buyReward" data-tier="${r[0]}" ${profile?.battle_pass&&((profile?.battle_xp||0)>=r[0]*100)?"":"disabled"}>Claim</button></div>`).join("");$$('[data-tier]').forEach(b=>b.onclick=()=>claimReward(Number(b.dataset.tier)))}
function updatePass(){renderPass();const owned=!!profile?.battle_pass;$("#passStatus").textContent=owned?`ACTIVE · ${Math.floor((profile?.battle_xp||0)/100)}/10 tiers`:"NOT OWNED";$("#bpProgress").textContent=user?`Battle XP: ${profile?.battle_xp||0} · Next tier: ${Math.max(0,100-((profile?.battle_xp||0)%100))} XP`:"Sign in to see your progress.";$("#buyPass").disabled=!user||owned;$("#buyPass").textContent=owned?"Battle Pass Owned":"Buy Battle Pass — 🪙 2,500"}
async function claimReward(tier){const r=await db.rpc("claim_battle_reward",{p_tier:tier});if(r.error)toast(r.error.message);else{toast("🎁 Battle Pass reward claimed!");refresh()}}
$("#buyPass").onclick=async()=>{if(!user)return needLogin();const r=await db.rpc("buy_battle_pass");if(r.error)toast(r.error.message);else{toast("🎟️ Battle Pass unlocked!");refresh()}};
async function daily(){if(!user)return;const r=await db.rpc("claim_daily_reward");if(r.error)toast(r.error.message);else if(r.data?.claimed)toast(`🌞 Daily reward: +${r.data.coins} coins and +${r.data.xp} Battle XP!`)}
async function renderProfile(){if(!user)return;const inv=await db.from("inventory").select("item_id").eq("user_id",user.id);const vip=profile?.vip?"👑 VIP":"";const admin=profile?.is_admin?"👑 ADMIN · ∞ COINS":"";$("#profileContent").innerHTML=`<div class="profile"><div class="avatar">🧑</div><div><span class="eyebrow">PLAYER PROFILE</span><h1>${esc(profile?.username||"Player")}</h1><p>${admin||vip||"Community Player"}</p><p>🪙 ${profile?.is_admin?"∞":profile?.coins||0} Forger Coins</p><p>Games created: ${profile?.games_created||0} · Plays: ${profile?.plays||0}</p><p>Battle XP: ${profile?.battle_xp||0} · ${profile?.battle_pass?"Battle Pass ACTIVE":"No Battle Pass"}</p><p>Cosmetics owned: ${inv.data?.length||0}</p></div></div><hr><p class="hint">Daily rewards, coins, games, VIP and inventory are stored online.</p><button class="primary" id="dailyBtn">🌞 Claim Daily Reward</button> <button class="secondary" id="logout2">Sign out</button>`;$("#logout2").onclick=async()=>{await db.auth.signOut();refresh()};$("#dailyBtn").onclick=daily}
$("#search").oninput=loadGames;$("#sort").onchange=loadGames;
db.auth.onAuthStateChange(()=>setTimeout(refresh,0));
renderPass();renderShop();refresh();
