const GAMES=[
{id:"snake",name:"Neon Snake",cat:"arcade",icon:"🐍",desc:"Grow your neon snake and chase the high score."},
{id:"clicker",name:"Crystal Clicker",cat:"arcade",icon:"💎",desc:"Click fast, build a combo and forge crystals."},
{id:"reaction",name:"Reaction Rush",cat:"action",icon:"⚡",desc:"Wait for green, then react as quickly as possible."},
{id:"memory",name:"Memory Match",cat:"puzzle",icon:"🧠",desc:"Flip cards and match every pair."},
{id:"dodger",name:"Space Dodger",cat:"action",icon:"🚀",desc:"Dodge falling asteroids for as long as you can."},
{id:"tictactoe",name:"Tic Tac Toe",cat:"classic",icon:"⭕",desc:"Challenge the browser in the classic grid game."}
];
const state=JSON.parse(localStorage.getItem("arcadeforge")||'{"coins":123,"played":0,"best":0,"favs":[],"scores":{},"achievements":[]}');
const save=()=>localStorage.setItem("arcadeforge",JSON.stringify(state));
const toast=m=>{let t=document.querySelector("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)};
function stats(){coinStat.textContent=state.coins;playedStat.textContent=state.played;bestStat.textContent=state.best;achievementStat.textContent=state.achievements.length}
function card(g){return `<article class="game-card"><button class="fav ${state.favs.includes(g.id)?"on":""}" data-fav="${g.id}">${state.favs.includes(g.id)?"★":"☆"}</button><div class="game-icon">${g.icon}</div><h3>${g.name}</h3><p>${g.desc}</p><button class="play" data-play="${g.id}">Play →</button></article>`}
function render(filter="all",q=""){let arr=GAMES.filter(g=>(filter==="all"||g.cat===filter)&&(`${g.name} ${g.desc}`.toLowerCase().includes(q.toLowerCase())));gameGrid.innerHTML=arr.map(card).join("")||"<p class='muted'>No games found.</p>";renderFavs()}
function renderFavs(){let a=GAMES.filter(g=>state.favs.includes(g.id));favoriteGrid.innerHTML=a.map(card).join("");noFavs.style.display=a.length?"none":"block"}
function leaderboard(){let rows=GAMES.map(g=>[g.name,state.scores[g.id]||0]).sort((a,b)=>b[1]-a[1]);leaderboardTable.innerHTML=rows.map((r,i)=>`<div class="row"><b>${i+1}</b><span>${r[0]}</span><span>${r[1]}</span></div>`).join("")}
function challenge(){challengeList.innerHTML=[["Play any game","Complete one game today","✓"],["Reach 100 points","Set a score of 100+","100"],["Favourite a game","Save a game for later","★"]].map(x=>`<div class="challenge"><b>${x[2]} &nbsp; ${x[0]}</b><small>${x[1]}</small></div>`).join("")}
function finish(id,score){state.played++;state.coins+=10;state.best=Math.max(state.best,score);state.scores[id]=Math.max(state.scores[id]||0,score);if(score>=100&&!state.achievements.includes("100"))state.achievements.push("100");save();stats();leaderboard();toast(`+10 coins · Score ${score}`)}
function openGame(id){modal.classList.remove("hidden");let g=GAMES.find(x=>x.id===id);gameArea.innerHTML=`<div class="game-ui"><div class="game-icon">${g.icon}</div><h2>${g.name}</h2><div id="playSpace"></div></div>`;({clicker:clicker,reaction:reaction,memory:memory,tictactoe:tictactoe,snake:snake,dodger:dodger}[id])()}
function clicker(){playSpace.innerHTML=`<p>Click the crystal as many times as you can in 10 seconds.</p><div class="big" id="clickScore">0</div><button class="click-target" id="crystal">💎</button><p>Time: <b id="clickTime">10</b></p>`;let s=0,t=10,go=true;crystal.onclick=()=>{if(go){s++;clickScore.textContent=s}};let iv=setInterval(()=>{t--;clickTime.textContent=t;if(t<=0){go=false;clearInterval(iv);finish("clicker",s)}},1000)}
function reaction(){playSpace.innerHTML=`<p id="reactText">Click START, wait for the screen to change, then click as fast as possible.</p><button class="btn primary" id="reactBtn">START</button>`;reactBtn.onclick=()=>{reactBtn.disabled=true;reactText.textContent="Wait...";let delay=1200+Math.random()*3000;setTimeout(()=>{let start=performance.now();reactText.textContent="GO!";reactBtn.disabled=false;reactBtn.textContent="CLICK!";reactBtn.onclick=()=>{let ms=Math.round(performance.now()-start);let score=Math.max(1,1000-ms);reactText.textContent=`Reaction: ${ms} ms`;finish("reaction",score);reactBtn.textContent="PLAY AGAIN";reactBtn.onclick=reaction}},delay)}}
function memory(){let vals=["🍒","⭐","🚀","👾","💎","🔥","🎮","🪐"],deck=[...vals,...vals].sort(()=>Math.random()-.5),open=[],matched=0;playSpace.innerHTML=`<div class="memory" id="memoryGrid">${deck.map((_,i)=>`<button data-i="${i}">?</button>`).join("")}</div><p>Pairs: <b id="pairs">0</b>/8</p>`;document.querySelectorAll(".memory button").forEach(b=>b.onclick=()=>{let i=+b.dataset.i;if(open.length===2||open.includes(i)||b.textContent!=="?")return;b.textContent=deck[i];open.push(i);if(open.length===2){let [a,c]=open;if(deck[a]===deck[c]){matched++;pairs.textContent=matched;open=[];if(matched===8)finish("memory",800)}else setTimeout(()=>{document.querySelectorAll(".memory button")[a].textContent="?";document.querySelectorAll(".memory button")[c].textContent="?";open=[]},650)}})}
function tictactoe(){let board=Array(9).fill(""),turn="X";playSpace.innerHTML=`<div class="tic">${board.map((_,i)=>`<button data-i="${i}"></button>`).join("")}</div><p id="ticMsg">Your turn (X)</p>`;document.querySelectorAll(".tic button").forEach(b=>b.onclick=()=>move(+b.dataset.i));function move(i){if(board[i]||turn!=="X")return;board[i]="X";draw();if(win("X"))return end(100);if(board.every(Boolean))return end(50);turn="O";setTimeout(ai,300)}function ai(){let free=board.map((x,i)=>x?null:i).filter(x=>x!==null);if(!free.length)return;board[free[Math.floor(Math.random()*free.length)]]="O";draw();if(win("O"))end(0);else if(board.every(Boolean))end(50);else turn="X";ticMsg.textContent="Your turn (X)"}function draw(){document.querySelectorAll(".tic button").forEach((b,i)=>b.textContent=board[i])}function win(p){return [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(a=>a.every(i=>board[i]===p))}function end(s){document.querySelectorAll(".tic button").forEach(b=>b.disabled=true);ticMsg.textContent=s===100?"You win!":s===0?"Computer wins!":"Draw!";finish("tictactoe",s)}}
function snake(){playSpace.innerHTML=`<canvas class="game-canvas" id="snakeCanvas" width="500" height="350"></canvas><p>Use arrow keys or WASD. Eat the red food.</p><b id="snakeScore">0</b>`;let c=snakeCanvas,x=c.getContext("2d"),s=20,pos=[10,8],dir=[1,0],food=[18,10],score=0,alive=true;function key(e){let k=e.key.toLowerCase(),d={arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0]}[k];if(d&&!(d[0]===-dir[0]&&d[1]===-dir[1]))dir=d}window.addEventListener("keydown",key);let body=[...Array(5)].map((_,i)=>[pos[0]-i,pos[1]]);let iv=setInterval(()=>{if(!alive)return;let h=[body[0][0]+dir[0],body[0][1]+dir[1]];if(h[0]<0||h[0]>=25||h[1]<0||h[1]>=17||body.some(p=>p[0]===h[0]&&p[1]===h[1])){alive=false;clearInterval(iv);window.removeEventListener("keydown",key);finish("snake",score);return}body.unshift(h);if(h[0]===food[0]&&h[1]===food[1]){score+=10;snakeScore.textContent=score;food=[Math.floor(Math.random()*25),Math.floor(Math.random()*17)]}else body.pop();x.fillStyle="#090811";x.fillRect(0,0,c.width,c.height);x.fillStyle="#a855f7";body.forEach(p=>x.fillRect(p[0]*s,p[1]*s,s-2,s-2));x.fillStyle="#ef4444";x.fillRect(food[0]*s,food[1]*s,s-2,s-2)},120)}
function dodger(){playSpace.innerHTML=`<canvas class="game-canvas" id="dodgeCanvas" width="500" height="350"></canvas><p>Move with ← → or A/D and avoid the falling blocks.</p><b id="dodgeScore">0</b>`;let c=dodgeCanvas,x=c.getContext("2d"),px=230,score=0,alive=true,blocks=[];function key(e){let k=e.key.toLowerCase();if(k==="arrowleft"||k==="a")px-=25;if(k==="arrowright"||k==="d")px+=25;px=Math.max(0,Math.min(460,px))}window.addEventListener("keydown",key);let iv=setInterval(()=>{if(!alive)return;if(Math.random()<.25)blocks.push({x:Math.random()*470,y:-20,v:3+Math.random()*3});x.fillStyle="#090811";x.fillRect(0,0,500,350);x.fillStyle="#22d3ee";x.fillRect(px,315,40,18);x.fillStyle="#ef4444";blocks.forEach(b=>{b.y+=b.v;x.fillRect(b.x,b.y,20,20);if(b.y>300&&b.x<px+40&&b.x+20>px)alive=false});blocks=blocks.filter(b=>b.y<370);score++;dodgeScore.textContent=score;if(!alive){clearInterval(iv);window.removeEventListener("keydown",key);finish("dodger",score)}},40)}
document.addEventListener("click",e=>{let p=e.target.closest("[data-play]"),f=e.target.closest("[data-fav]");if(p)openGame(p.dataset.play);if(f){let id=f.dataset.fav;state.favs=state.favs.includes(id)?state.favs.filter(x=>x!==id):[...state.favs,id];save();render();toast(state.favs.includes(id)?"Added to favourites":"Removed from favourites")}})
search.oninput=()=>render(document.querySelector(".filter.active").dataset.filter,search.value);
filters.onclick=e=>{if(!e.target.classList.contains("filter"))return;document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));e.target.classList.add("active");render(e.target.dataset.filter,search.value)};
randomBtn.onclick=()=>openGame(GAMES[Math.floor(Math.random()*GAMES.length)].id);
closeModal.onclick=()=>modal.classList.add("hidden");modal.onclick=e=>{if(e.target===modal)modal.classList.add("hidden")};
themeBtn.onclick=()=>{document.body.classList.toggle("light");themeBtn.textContent=document.body.classList.contains("light")?"☀":"☾";localStorage.setItem("af-theme",document.body.classList.contains("light")?"light":"dark")};
if(localStorage.getItem("af-theme")==="light"){document.body.classList.add("light");themeBtn.textContent="☀"}
render();stats();leaderboard();challenge();
